version: '3.7'

networks:
  dev-net:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - "db"
    networks:
      - dev-net
  
  db:
    container_name: 'postgres-db'
    image: postgres:9.5
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=airport
    networks:
      - dev-net