version: 2.1
jobs:
  deploy-to-prod:
    machine: true
    steps:
      - checkout
      - run:
          name: Buid and push docker image to registry
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            PSQL_CONNECTION_STRING=$CONNECTION_STRING
            ./build.sh $PSQL_CONNECTION_STRING
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag airport-cw-api:$TAG registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build_and_test:
    jobs:
      - deploy-to-prod:
          filters:
            branches:
              only:
                - master