version: 2.1
jobs:
  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            PSQL_CONNECTION_STRING=$CONNECTION_STRING
            ./build.sh $PSQL_CONNECTION_STRING
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Push docker image to registry
          command: |
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag rinoceronte registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a $HEROKU_APP_NAME
workflows:
  build_and_test:
    jobs:
      - build-docker-image
      - deploy:
          requires:
            - build-docker-image
          filters:
            branches:
              only:
                - master
