version: 2.1
jobs:
  deploy-to-prod:
    machine: true
    steps:
      - checkout
      - run:
          name: Buid and push docker image to registry
          command: |
            PSQL_CONNECTION_STRING=$CONNECTION_STRING
            ./build.sh $PSQL_CONNECTION_STRING
            TAG=$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM
            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
            docker tag $TAG registry.heroku.com/$HEROKU_APP_NAME/web
            docker push registry.heroku.com/$HEROKU_APP_NAME/web
            curl https://cli-assets.heroku.com/install.sh | sh
            heroku container:release web -a $HEROKU_APP_NAME
  deploy-to-docker-hub:
    machine: true
    steps:
      - checkout
      - run:
          name: Buid and push docker image to dockerhub registry
          command: |
            PSQL_CONNECTION_STRING=$CONNECTION_STRING
            ./build.sh $PSQL_CONNECTION_STRING
            TAG=$CIRCLE_BRANCH:$CIRCLE_BUILD_NUM
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push $TAG
workflows:
  build_and_test:
    jobs:
      - deploy-to-prod:
          filters:
            branches:
              only:
                - master
      - deploy-to-docker-hub:
          filters:
            branches:
              ignore:
                - master