version: 2.1
jobs:
  build:
    machine: true
    build-docker-image:
      requires:
        - build
      steps:
        - checkout
        - run:
            name: Build docker image
            command: |
              PSQL_CONNECTION_STRING=$CONNECTION_STRING
              ./build.sh $PSQL_CONNECTION_STRING
    deploy:
      requires:
        - build-docker-image
      steps:
        - checkout
        - run:
            name: Push docker image to registry
            command: |
              docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
              docker tag rinoceronte registry.heroku.com/$HEROKU_APP_NAME/web
              docker push registry.heroku.com/$HEROKU_APP_NAME/web
              curl https://cli-assets.heroku.com/install.sh | sh
              heroku container:release web -a $HEROKU_APP_NAME
      filters:
        branches:
          only:
            - master
#    - deploy-to-docker-hub:
#        requires:
#          - build-docker-image
#        steps:
#          - checkout
#          - run:
#              name: Push docker image to dockerhub registry
#              command: |
#                TAG=$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
#                echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
#                docker push airport-cw-demo:$TAG
#        filters:
#          branches:
#            ignore:
#              - master