version: 2.1
jobs:
 build:
   machine: true
   commands:
     - bash ./build.sh
   steps:
     - checkout 
     - run: |
         docker info
         docker --build-arg CONNECTION_STRING=$CONNECTION_STRING -t rinoceronte -f Dockerfile .

     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag rinoceronte registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME
