INSERT INTO country(name, code)
VALUES ('Italy', 'IT'),
       ('China', 'CN'),
       ('United Kingdom', 'GB'),
       ('United Arab Emirates', 'AE'),
       ('Spain', 'ES'),
       ('Singapore', 'SG'),
       ('United States', 'US'),
       ('Germany', 'DE'),
       ('France', 'FR');
       
INSERT INTO airport(name,city,country_id)
VALUES ('Hartsfield Jackson Atlanta Intl','Atlanta',7),
        ('Chicago Ohare Intl','Chicago',7),
        ('Capital Intl','Beijing',2),
        ('Heathrow','London', 3),
        ('Charles De Gaulle','Paris', 9),
        ('Los Angeles Intl','Los Angeles', 7),
        ('Frankfurt Main','Frankfurt', 8),
        ('Dallas Fort Worth Intl','Dallas-Fort Worth', 7),
        ('John F Kennedy Intl','New York', 7),
        ('Pudong','Shanghai', 2),
        ('Changi Intl','6', 6),
        ('Barcelona','Barcelona', 5),
        ('Denver Intl','Denver', 7),
        ('Miami Intl','Miami', 7),
        ('Dubai Intl','Dubai', 4),
        ('Gatwick','London', 3),
        ('Baiyun Intl','Guangzhou', 2),
        ('Fiumicino','Rome', 1);
